version: '3.7'
services:
  django-tkun:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'django-tkun'
    command: python manage.py runserver 0.0.0.0:80
    ports:
      - '8080:80'
    volumes:
      - .:/django-api/
    depends_on:
      - sql-tkun

  sql-tkun:
    image: mysql:5.7
    container_name: 'sql-tkun'
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '12345678'
      MYSQL_ROOT_PASSWORD: '12345678'
    ports:
      - '36:3306'
    # volumes:
    #   - ./db:/var/lib/mysql
