# Generated by Django 4.0.4 on 2022-06-03 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendancetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetable',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
